version: '3.8'
services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile-tomcat
    container_name: tomcat_container
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - tomcat_data:/usr/local/tomcat/logs
    depends_on:
      - db
  db:
      image: mariadb
      container_name: mariadb_container
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=pass
        - MYSQL_DATABASE=bsu
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pass
      ports:
        - "3306:3306"
      volumes:
        - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data:
  tomcat_data:
