version: '3.8'
services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile-tomcat
    container_name: tomcat_container
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./target/bsu-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/app.war
  db:
      image: mariadb
      container_name: mariadb_container
      restart: always
      environment:
          MARIADB_PASSWORD: PASSWORD
          MARIADB_USER: USER
          MARIADB_DATABASE: bsu
      ports:
        - "3306:3306"
      volumes:
        - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data:
