version: '3.8'
services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tomcat-java-1
    restart: 'no'
    ports:
      - "8080:8080"
    volumes:
      - ./target/bsu-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/app.war
